packages:
  - '.'

overrides:
  headers-polyfill: 5.0.1
  parse5: ^8.0.0

onlyBuiltDependencies:
  - cypress
  - esbuild
  - msw

ignoreBuildScripts: false

allowBuilds:
  cypress: true
  esbuild: true
  msw: true
