name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v4.4.0
        with:
          version: latest

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1

      - name: Install dependencies
        run: pnpm i

      - name: Validate
        run: pnpm run-p lint test:ci
